- sources/Makefile.users
- sources/lib/frontend/frontend.ml
- sources/lib/frontend/frontend.mli
- sources/lib/frontend/parsers.ml
- sources/lib/util/options.ml
- sources/lib/util/options.mli
- sources/tools/gui/main_gui.ml
- sources/tools/text/main_text.ml
@mebsout What do you think about this ? I'm not sure for the GUI
>  add the ability to use the given timelimit per goal. This is important when we have multiple goals per file

- sources/lib/reasoners/satml.ml
- sources/lib/reasoners/satml.mli
- sources/lib/reasoners/satml_frontend.ml
- TODO: reintroduce satml.mli before merge
> Improve sat ml

- sources/lib/frontend/cnf.ml
- sources/lib/frontend/parsed_interface.ml
- sources/lib/frontend/parsed_interface.mli
- sources/lib/frontend/typechecker.ml
- sources/lib/structures/formula.ml
- sources/lib/structures/formula.mli
- sources/lib/structures/parsed.ml
- sources/lib/structures/parsed.mli
- sources/lib/structures/typed.ml
- sources/lib/structures/typed.mli
- sources/parsers/why/why_lexer.mll
- sources/parsers/why/why_parser.mly
- sources/tools/gui/annoted_ast.ml
- sources/tools/gui/annoted_ast.mli
fixes https://github.com/OCamlPro/alt-ergo/issues/89
> support xor operator: translated to "not (. <-> .)" in Formula

- sources/parsers/common/parsers.ml
When an extension is not associated with a parser, try the parser
corresponding to the language provided with option '-default-lang'
> Accept file extensions that are not associated with parsers

- non-regression/gui/display_farray_1.mlw
- sources/tools/gui/annoted_ast.ml
> Also translate/downgrade farrays in annoted_ast

- sources/lib/reasoners/theory.ml
- sources/lib/structures/expr.ml
- sources/lib/structures/expr.mli
- sources/lib/structures/symbols.ml
- sources/lib/structures/symbols.mli
- sources/lib/structures/ty.ml
- sources/lib/structures/ty.mli
- sources/lib/structures/typed.ml
- sources/lib/structures/typed.mli
- sources/lib/structures/xliteral.ml
- sources/lib/structures/xliteral.mli
- sources/tools/gui/annoted_ast.ml
- sources/tools/gui/gui_config.ml
- sources/tools/gui/gui_config.mli
extend structures in Expr, Symbols, Ty, Typed, Xliteral to prepare integration of ADTs
> [transition commit] add structures related to ADTs in backend

- .travis.yml
> Run opam update if needed in the travis script

- .gitignore
- .travis.yml
- extra/index.txt
- extra/make_doc.sh
- extra/travis_doc_test.sh
- extra/travis_install_test.sh
- extra/travis_local_test.sh
- sources/Makefile
- sources/dune
- sources/lib/dune
- sources/lib/frontend/input.mli
- sources/lib/index.mld
- sources/lib/structures/expr.mli
- sources/lib/structures/ty.mli
- sources/lib/structures/typed.mli
- sources/lib/util/emap.mli
- sources/lib/util/gc_debug.mli
- sources/lib/util/hconsing.mli
- sources/lib/util/iheap.mli
- sources/lib/util/lists.mli
- sources/lib/util/loc.mli
- sources/lib/util/myDynlink.mli
- sources/lib/util/myUnix.ml
- sources/lib/util/myUnix.mli
- sources/parsers/dune
- sources/parsers/index.mld
- sources/tools/gui/dune
- sources/tools/gui/index.mld
- sources/tools/text/dune
- sources/tools/text/index.mld
This PR first adds some documentation to some module interfaces.
More importantly, it sets up automatic documentation build and checking in the travis CI, as well as automatic uploading of the generated html documentation on the gh-pages branch.
> More documentation

- sources/lib/reasoners/arrays_rel.ml
Should close #209 
cc @mebsout  when he returns.
> Fix potential typo in arrays_rel.ml

- sources/INSTALL.md
- sources/Makefile
> Add targets to build release version of single targets

- sources/lib/frontend/frontend.ml
- sources/lib/frontend/frontend.mli
- sources/lib/reasoners/fun_sat.ml
- sources/lib/reasoners/sat_solver_sig.ml
- sources/lib/reasoners/sat_solver_sig.mli
- sources/lib/reasoners/satml.ml
- sources/lib/reasoners/satml.mli
- sources/lib/reasoners/satml_frontend.ml
- sources/lib/structures/profiling.ml
- sources/lib/structures/profiling.mli
- sources/lib/util/options.ml
- sources/lib/util/options.mli
- sources/tools/gui/main_gui.ml
- sources/tools/text/main_text.ml
Correct steps bound issue where when the option is set the number of total steps differs from normal behavior. Use int instead of Int64 for steps_bounds
> Correct steps bound issue

- .travis.yml
- sources/lib/frontend/cnf.ml
- sources/lib/frontend/parsed_interface.mli
- sources/lib/reasoners/adt.ml
- sources/lib/reasoners/adt_rel.ml
- sources/lib/reasoners/intervalCalculus.ml
- sources/lib/reasoners/ite_rel.ml
- sources/lib/reasoners/records.ml
- sources/lib/reasoners/satml.ml
- sources/lib/reasoners/satml_frontend.ml
- sources/lib/reasoners/shostak.ml
- sources/lib/structures/expr.ml
- sources/lib/structures/satml_types.ml
- sources/lib/structures/ty.ml
- sources/lib/util/options.ml
Code modification to allow the use of the newest version of ocp-indent with [@ocaml.ppwarning ...]
> Move to the newest version of ocp-indent

- sources/lib/dune
- sources/lib/frontend/frontend.ml
- sources/lib/reasoners/arith.ml
- sources/lib/reasoners/fun_sat.ml
- sources/lib/reasoners/inequalities.ml
- sources/lib/reasoners/intervalCalculus.ml
- sources/lib/reasoners/matching.ml
- sources/lib/reasoners/satml.ml
- sources/lib/reasoners/satml_frontend.ml
- sources/lib/reasoners/uf.ml
- sources/lib/util/options.ml
- sources/lib/util/options.mli
- sources/lib/util/steps.ml
- sources/lib/util/steps.mli
- sources/tools/text/main_text.ml
These are our patches for improving alt-ergo steps behavior in some cases.
Note that this patch reintroduces the bug that we reported on issue #250 (same reproducer as on that issue, communicated privately), so likely some fix is needed.
> Patches for steps behavior

- CONTRIBUTING.md
- COPYING.md
- INSTALL.md
- LICENSE.md
- README.md
- USAGE.md
- dune-project
Hi,
First I just wanted to switch some links to https, bu then I decided to also clean the readme. I also added minor things like a link to Why3's website etc.
EDIT: also, the link in the description of the repository is using http and not https, but I can't change that myself, it would be nice if someone could do it :)
> clean the readme

- src/bin/gui/connected_ast.ml
Force the fui to use native parser for the manual addition of instances and triggers
> Fix gui trigger inst

- src/lib/reasoners/theory.ml
> fix theory assumed debug infos printing

- src/lib/reasoners/theory.ml
Fixes https://github.com/OCamlPro/alt-ergo/issues/313
When the case-split module's choices are contradicted by the SAT
solver, case-split tries to replay its choices (in chronological
order) to find a new non-conflicting state. This may force the
case-split module to "ignore" some of its guesses/decisions it made
previously.
Because theories solvers may introduce fresh variables that are
not in the original problem, case-split decisions (and
implications) containing fresh variables are removed before
trying to find a new "non-conflicting state".
The bug fixed here is due to the fact that some case-split
choices/decisions (introduced with some explanations `Fresh n`)
are removed as explained above, but their consequences are likely
still in the case-split's context (these consequences are …
> Fix a bug in case-split that causes Fresh explanation to escape their scope

- src/lib/frontend/cnf.ml
- src/lib/structures/expr.ml
- src/lib/structures/expr.mli
- src/lib/structures/typed.ml
- src/lib/structures/typed.mli
fixes https://github.com/OCamlPro/alt-ergo/issues/245
But the example provided in that issue triggers another bug, which should be fixed by https://github.com/OCamlPro/alt-ergo/pull/337
> defining terms of recursive functions

- configure
> Replace bash by sh in configure script

- sources/CHANGES
- sources/Makefile
- sources/alt-ergo-lib.opam
- sources/alt-ergo-parsers.opam
- sources/alt-ergo.opam
- sources/altgr-ergo.opam
- sources/configure
- sources/configure.ml
- sources/lib/util/version.ml
This Release is done to fix #351
> 2.3.3 minor

- configure.ml
Two main changes:
- Add mandir option
- Better error message without opam
> Configure script tweaks

- src/bin/common/parse_command.ml
- src/bin/text/main_text.ml
- src/lib/frontend/frontend.ml
- src/lib/frontend/typechecker.ml
- src/lib/reasoners/intervalCalculus.ml
- src/lib/structures/errors.ml
- src/lib/structures/errors.mli
- src/lib/util/options.ml
- src/lib/util/options.mli
- src/lib/util/printer.ml
- src/parsers/psmt2_to_alt_ergo.ml
This pr aim to add a check for the status of the smt2 files. A warning / error is raised if the file is known to be sat (resp unsat) and Alt-ergo return unsat (resp sat).
> Next+smt2 status

- src/bin/text/main_text.ml
Should fix https://github.com/OCamlPro/alt-ergo/issues/406
> Catch all possible timeout in bin

- src/lib/reasoners/arrays.ml
- src/lib/reasoners/records.ml
- src/lib/reasoners/shostak.ml
- src/lib/reasoners/uf.ml
- src/lib/structures/expr.ml
- src/lib/structures/expr.mli
- term depth was not accurate in case of f(true) and f(false)
> fix computation of terms depth + use E.const_term instead of E.depth t = 1

- src/lib/reasoners/uf.ml
- src/lib/structures/expr.ml
Global results (cmp with next branch):
**Valid / Unsat**
  | AE-format
-- | --
ae-1-next | 51525 (85.42%) (13782s)
ae-4-fix-depth-p2 | 51564 (85.49%) (13814s)
**Unique Valid / Unsat**
  | AE-format
-- | --
ae-1-next | 155
ae-4-fix-depth-p2 | 194
Details:
  | Bware-DAB | Bware-RCS3 | Bware-p4 | Bware-p4-NGOP | Bware-p9 | Bware-p9-NGOP | CoLiS-interpreter-no-split | CoLiS-interpreter-split-goal-right+intro | CoLiS-path_resolution-no-split | CoLiS-path_resolution-split-goal-right+intro | Frama-C | Frama-C-DS | SPARK-Soprano | cubicle-FLASH | open-acslbyexample-2016-11-30 | why3-no-split | why3-split_vc
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ae-1-next | 768 (100.00%) (115s) | 2234 (99.02%) (699s) | 9288 (99.43%) (1581s) | 1180 (96.80%) (272s) | …
> Expr: swap tags in compare: older terms are smaller (if same depth).

- src/lib/reasoners/fun_sat.ml
- src/lib/reasoners/satml_frontend.ml
This regression was found after running some test with  the following results
  | AE-format
-- | --
cdcl | 51734 (85.77%) (22106s)
cdcl-fixed | 51855 (85.97%) (23153s)
tableaux | 52196 (86.53%) (23440s)
tableaux-fixed | 52416 (86.90%) (29975s)
> Set trigger-vars as default in greedy instantiation

- src/lib/frontend/cnf.ml
- src/lib/reasoners/arith.ml
- src/lib/reasoners/fun_sat.ml
- src/lib/structures/expr.ml
- src/lib/structures/expr.mli
- src/lib/structures/satml_types.ml
Currently testing on internal benchs. I made some rewriting in the code in the meantime, but could be quickly fixed to be sure no regressions are introduced
> Improvements

- src/bin/js/worker_js.ml
- src/lib/util/options.ml
Fix issues with set_is_gui when this function is used multiple time.
Add handler for exceptions in the worker and return an Error status
> Fix worker
