OCamlPro/alt-ergo

sources/lib/frontend/frontend.ml
@bobot. I just tested with latest version of Frama-C. Putting the name of the goal is fine. But not expliciting that resolution time is given in seconds.
=> small patch in Alt-Ergo to be compatible with Frama-C

sources/lib/reasoners/matching.ml
@bobot @correnson
I noticed a very bad user-given multi-trigger in axioms `separated_1` of file `Memory.why`. This makes Alt-Ergo stuck in the instantiation module, and I decided to ignore "big" multi-triggers.
Maybe you should rewrite the axiom, as follows:
```
axiom separated_1 : forall p:addr, q:addr. forall a:int, b:int
[separated p a q b].
separated p a q b ->
forall i:int, j:int  [Mk_addr (base p) i, Mk_addr (base q) j].
(Int.(<=) (offset p) (i)) /\ (Int.(<) (i) ((Int.(+) (offset
p) (a)))) -> (Int.(<=) (offset q) (j)) /\ (Int.(<) (j) ((Int.(+) (offset
q) (b)))) -> not ((Mk_addr (base p) i) = (Mk_addr (base q) j))
```
=> ignore multi-triggers with a size greater than a given constant (default const = 2)

sources/lib/frontend/triggers.ml, sources/lib/frontend/triggers.mli, sources/lib/frontend/typechecker.ml
This PR tries and factorize trigger inference so that it can more easily be moved outside the typechecker. The trigger inference is still done in the typechecker, but only at one place, when typechecking a whole input file.
=> Separate Typing from Trigger inference

non-regression/run_invalid.sh, non-regression/run_valid.sh, sources/lib/reasoners/fun_sat.ml, sources/lib/reasoners/satml.ml, sources/lib/reasoners/satml.mli, sources/lib/reasoners/satml_frontend.ml, sources/lib/reasoners/satml_frontend_hybrid.ml, sources/lib/structures/satml_types.ml, sources/lib/util/options.ml, sources/lib/util/options.mli
Add a new option "-no-tableaux-cdcl-in-theories" for disabling Tableaux reduction model for the theories.
=> Four versions of SAT-solvers: Tableaux, CDCL, Tableaux-with-CDCL, CDCL-with-Tableaux

sources/examples/lib_usage.ml, sources/lib/dune, sources/lib/frontend/input.ml, sources/lib/frontend/input.mli, sources/lib/frontend/typechecker.ml, sources/lib/frontend/typechecker.mli, sources/lib/structures/typed.ml, sources/lib/structures/typed.mli, sources/lib/util/options.ml, sources/lib/util/options.mli, sources/parsers/parsers.ml, sources/tools/gui/connected_ast.ml, sources/tools/gui/main_gui.ml, sources/tools/text/dune, sources/tools/text/main_input.ml, sources/tools/text/main_text.ml
This PR creates the notion of input method.
An input method is a black box that outputs a list of typed statements, from a given filename. Currently, the only input method defined is the legacy one, using the AltErgoParsers lib and the builtin typechecker (as well as the psmt2 to native translation). Future input methods should include a direct psmt2 input method (to avoid typechecking twice), and a dolmen input method.
The choice of input method is currently done using a command line argument named "frontend".
Additionnally, this PR moves the generation of new ids for typed formulas from the typechecker to the `typed` module, as future input methods should not depend on the builtin typechecker, but only on the `typed` module.
=> Abstract over input method

sources/parsers/why_parser.mly
recent changes in why_lexer.mll, replaced the ID "?" with ""
=> fix in the native parser for floating-point's semantic triggers

LICENSE.md
Fixes https://github.com/OCamlPro/alt-ergo/issues/176
=> fix license: AB-why3 plugin has LGPL license

sources/INSTALL.md, sources/lib/util/options.ml
This PR complements the recently merged #240 , by updating the documentation of the `-where` option in the alt-ergo binary, and adding a paragraph in `INSTALL.md` to explain that the preludes and plugins directories are relative to the executable.
=> Add some doc concerning relative include paths

sources/lib/reasoners/instances.ml, sources/lib/reasoners/intervalCalculus.ml, sources/lib/reasoners/intervals.ml, sources/lib/reasoners/intervals.mli, sources/lib/structures/explanation.ml, sources/lib/structures/explanation.mli
See the second commit message.
=> Fix Issue #248

sources/configure.ml
The `configure.ml` script added with the switch to dune unfortunately assumed at least opam 2 (because it used the `opam var` command). This add back support for `opam < 2` by using the `opam config var` command instead.
This should solve #254
=> Add support for opam < 2

sources/lib/frontend/cnf.ml, sources/lib/frontend/parsed_interface.ml, sources/lib/frontend/parsed_interface.mli, sources/lib/frontend/typechecker.ml, sources/lib/reasoners/adt_rel.ml, sources/lib/reasoners/arith.ml, sources/lib/reasoners/arith.mli, sources/lib/reasoners/arrays_rel.ml, sources/lib/reasoners/bitv_rel.ml, sources/lib/reasoners/ccx.ml, sources/lib/reasoners/enum_rel.ml, sources/lib/reasoners/intervalCalculus.ml, sources/lib/reasoners/ite_rel.ml, sources/lib/reasoners/records_rel.ml, sources/lib/reasoners/relation.ml, sources/lib/reasoners/sig_rel.mli, sources/lib/structures/expr.ml, sources/lib/structures/parsed.ml, sources/lib/structures/parsed.mli, sources/lib/structures/symbols.ml, sources/lib/structures/symbols.mli, sources/lib/structures/xliteral.ml, sources/lib/structures/xliteral.mli, sources/parsers/why_lexer.mll, sources/parsers/why_parser.mly, sources/preludes/fpa-theory-2019-10-08-19h00.why
- new non-linear arithmetic infix operator for exponentiation denoted '**', such that:
Typing:
`(u : Int) ** (v : Int)` is of type Int
`(u : Real) **. (v : Real)` is of type Real
`(u : Real) **. (v : Int)` is of type Real
`(u : Int) **. (v : Real)` is of type Real
`(u : Int **. (v : Int)` is of type Real
Interpretation:
u ** v is not interpreted, except when:
- u and v are constants (modulo theories) and v is integral, in which case, the result of u ** v is computed
- v is equal to 1 (modulo theories), in which case u ** v is equal to u
- v is equal to 0 (modulo theories), in which case u ** v is equal to 1
=> Add exponentiation operation, `**` in native Alt-Ergo syntax.

rsc/extra/deploy_doc.sh
Fix bug introduced in #287 where documentation deployment was not tested in the CI, only the build was tested.
=> Fix documentation deployment script

src/parsers/psmt2_to_alt_ergo.ml
This modification is mandatory for smtcomp2020 since no output can be print on stderr
=> Fix verbose for unsupported command in psmt2-frontend

.gitignore, Makefile
Useful for people using local opam switchs. Otherwise, make emacs edit tries to open all ml* files in _opam sub-dirs
=> ignore _opam dir if present (gitignore + make emacs-edit)

src/dune
Disable warning as error and optimisation for the dune dev profile. Add new profile to enable all warnings. Add some known warning flag as error in release profile since this warnings should be resolve for release
=> Fix dune warning flags

src/bin/common/signals.ml, src/bin/common/signals.mli, src/bin/text/main_text.ml
The gui used the vtalarm instead of alarm.
The cmdline used alarm instead of vtalarm.
This should fix #329
=> fix issue 329 that did not differentiate vtalarm and alarm signals.

src/lib/structures/expr.ml
This PR fixes the `Stack Overflow` in https://github.com/OCamlPro/alt-ergo/issues/315
As said in that issue, the `Stack Overflow` is raised when trying to infer multi-triggers for a big axiom, with the following characteristics:
```
4 bound vars:
'p1~3818'
'p2~3819'
'p3~3820'
'c~3821'
number of (non-var) terms containing these vars 31
size of powerset from these terms 1584291
size of smalltest multi-trigger = 3
size of biggest multi-trigger = 20
```
Since we have 4 bound vars (and no type variables), we expect the biggest multi-trigger that covers all these variables to have at most 4 elements. But here, a debug trace showed that `size of biggest multi-trigger = 20`.
This situation is due to the use of functions `Set.equal` (in `  if SSet.equal bv1 bv2 && Svty.equal vty1 vty2 then`) to …
=> Improve multi triggers inference

src/lib/frontend/cnf.ml, src/lib/frontend/typechecker.ml
This PR fixes issue https://github.com/OCamlPro/alt-ergo/issues/290.
A minimal example that reproduces the bug is the following:
```
type 'a t
logic f : 'a t -> 'a
logic rand : 'a -> bool
function func (x : 'a t) : bool =
forall i : int. rand(f(x))
logic U : int t
goal g: func(U)
```
During the transformation of the typed AST to expressions of type `Expr.t`, the function declaration becomes:
```
Axiom func:
forall x : 'a t.
func(x) = ( forall i : int. rand(f(x)))
```
But, because of a bug during the transformation, the type variable `'a` is (also) quantified/bound in the inner quantification (the inner quantification is seen as toplevel), which is not correct (type variables should be in prenex form). As a consequence:
- When instantiating, the substitution `{x |-> U , 'a |-> int}` fails …
=> Bugfix: type variables are not quantified in prenex form in Functions declarations of type bool

src/lib/structures/expr.ml
Fixes https://github.com/OCamlPro/alt-ergo/issues/335
let-in were not always re-constructed in the correct order.
For instance:
let x = e1 in
let y = h(x, e2) in
f(x,y) < g(y,x)
may become
let y = h(x, e2) in
let x = e1 in
f(x,y) < g(y,x)
which is incorrect, because 'x' escapes its scope.
=> Fix lifting/purification of expressions with let-in

src/lib/util/printer.ml
fixes https://github.com/OCamlPro/alt-ergo/issues/333
4 commits, 4 (small) changes in printer.ml
- no ANSI color in solver's final answer
- refactoring: provide the fmt for print_status_loc and print_status_value
- refactor print_status to show stats even in unsat mode (commented and in std_err)
eg.
```   
; File "foo.smt2", line 1, characters 1-17: Inconsistent assumption (0.0040) (0 steps)
; File "foo.smt2", line 2, characters 1-12: Valid (0.0041) (0 steps) (goal g)
unsat
```    
where the two first lines are commented and printed to std debug/err.
- [printer] log print_status_{inconsistent, preprocess} in fmt_dbg instead of fmt_std
For instance, if we have something like:
```
File "bar.ae", line 2, characters 1-14: Inconsistent assumption (0.0010) (0 steps)
File "bar.ae", line 2, …
```
=> Fix solver output

src/lib/reasoners/intervalCalculus.ml
In some situations, the constant c in an inequatily on integers:
p + c <= 0, is not an integer. In this case, it should be replaced with:
p + floor(c) <= 0
fixes https://github.com/OCamlPro/alt-ergo/issues/340
=> Bug fix in intervals deduction from FM results

src/lib/structures/expr.ml, src/lib/structures/typed.ml
bad simplification in eg `distinct (a, a, b)` should return `false` (`true` for `n_ary_eq`) instead of `distinct(a,b)`
=> fix simplification of distincts

src/lib/reasoners/fun_sat.ml, src/lib/reasoners/matching.ml, src/lib/structures/expr.ml
Now, we can easily detect Defns and Iff in Expr. Improve backward triggers for these constructs.
**Motivation:**
- Alt-Ergo (CDCL) timeouts after 3600 seconds on `p9_11-B_translation-OBF__hhgg_1.ae`
- Alt-Ergo (Tableaux) with this extension proves the formula in seconds with just backward (-like) reasoning
=> imporve backward-like reasoning in Tableaux

configure.ml
it's bad practice to call `opam` without `--readonly` from within an opam package, and could cause failures or deadlocks.
=> Fix opam call in configure.ml

src/lib/reasoners/fun_sat.ml, src/lib/reasoners/satml_frontend.ml
The goal of this PR is to delay the triggers-vars heuristic when Alt-Ergo perform a greedy instantiation round. This heuristic can be costly (time) but in certain cases allow a faster resolution.
This changes has been tested for both SAT. The global performance (time) has been improved
=> Add greedier instantiation round in both sat solver

rsc/extra/test_lib.sh, src/lib/models/models.ml, src/lib/reasoners/shostak.ml
Fixes https://github.com/OCamlPro/alt-ergo/issues/384
(The first example was already fixed in `models` branch)
=> [models] add case-split on internal bool terms

src/lib/reasoners/records.ml
These deductions should already be done by Shostak solver
=> disable deductions by congruence closure on record symbols

src/bin/common/parse_command.ml
Fixes https://github.com/OCamlPro/alt-ergo/issues/394
=> auto set option "fm_cross_limit = -1" (ie. infinity) if models-gen is set

src/lib/structures/expr.ml
Mainly for "Let x = e1 in e2" in cases where e1 is a cascade of Ites
=> Improve purification process in expressions

src/lib/frontend/cnf.ml
In few cases, skolemization outputs an non-purified expression, i.e. an expression with formulas inside terms that are not defined as let-bindings. This causes Alt-Ergo to fail on few examples.
This PR adds a purification step while building quantified formulas, which fixes the issue.
=> Purification bugfix
